name: Terraform and Markdown Checks

on:
  push:
    paths:
      - '**.tf'
      - '**.md'
      - '.github/workflows/terraform_checks.yaml'
    branches:
      - main
  pull_request:
    paths:
      - '**.tf'
      - '**.md'
      - '.github/workflows/terraform_checks.yaml'

jobs:
  lint-and-format:
    name: Lint and Format Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform fmt -check

      - name: TFLint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.review_dog_tflint }}

      - name: Markdown Lint
        uses: avto-dev/markdown-lint@v1

  docs:
    name: Generate Terraform Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install terraform-docs
        run: |
          wget https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
          tar -xvf terraform-docs-v0.15.0-linux-amd64.tar.gz
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate Docs for ec2_instance
        run: terraform-docs markdown table --output-template "<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->" modules\ec2_instance

      - name: Generate Docs for subnet
        run: terraform-docs markdown table --output-template "<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->" modules\subnet

      - name: Generate Docs for vpc
        run: terraform-docs markdown table --output-template "<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->" modules\vpc

      - name: Generate Docs for Root Directory 
        run: terraform-docs markdown table -c .terraform-docs.yml --output-template "<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->" .

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./modules/ec2_instance ./modules/subnet ./modules/vpc .
          git commit -m "Automated documentation update" || echo "No changes to commit"
          git push


