name: Generate Terraform Docs

on:
  push:
    paths:
      - '**.tf'
      - '**.md'
      - '.github/workflows/terraform_docs.yaml'
    branches:
      - main
  pull_request:
    paths:
      - '**.tf'
      - '**.md'
      - '.github/workflows/terraform_docs.yaml'

jobs:
   docs:
    name: Generate Terraform Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with: 
          token: ${{ secrets.gt_bot_auth }}

      - name: Install terraform-docs
        run: |
          wget https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
          tar -xvf terraform-docs-v0.16.0-linux-amd64.tar.gz
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate Docs for All Modules
        run: |
          for module_dir in modules/*; do
            if [ -d "$module_dir" ]; then
              echo "Generating docs for $module_dir ..."
              terraform-docs markdown table --output-template "<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->" "$module_dir" > "$module_dir/README.md"
            fi
          done

      # - name: Generate Docs for Root Directory 
      #   run: terraform-docs markdown table -c .terraform-docs.yml --output-template "<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->" .

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./modules/ec2_instance ./modules/subnet ./modules/vpc 
          git commit -m "Automated documentation update" || echo "No changes to commit"
          git push
        env:
          GT_BOT_AUTH: ${{ secrets.gt_bot_auth }}
